= SpringOne Platform 2016 : Easy Consumption of Microservices

== Anatomy of the Initializr

TBD

== Step 0: Initial Development Setup

Follow these steps to setup and configure your development environment to be able to customize the
Initializr web application:

* Fork and clone: https://github.com/spring-io/initializr.git [for this guide,
you can clone https://github.com/ssherwood/initializr which starts on commit
a415cdc671d93beb83c15b5c47a05e674574378f]

* Verify that you can actually build and run the project (this requires the https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-installing-spring-boot.html#getting-started-installing-the-cli[Spring Boot CLI])

....
% cd initializr-service
% spring run app.groovy
....

* Visit the running Initializr http://localhost:8080/[application].

* Once your sure its properly executing, quit out (ctrl-c) and then import the project into your
favorite IDE.  We will be using IntelliJ for this but any IDE will work.

IMPORTANT: When using the IDE for Initializr,  we've found it much easier to create a separate
module that represents a more traditional "main" class over using the CLI in initializr-service.
This will make it easier to take advantage of devtools and the debugger.

* Create a new Maven module 'initializr-app'
** Select the root "initializr" in Project view and right-click: New > Module
** Leave "Maven" selected and click Next
** Set artifactId :: initializr-app and click Next
** Set Module name :: initializr-app and click Finish

Now you have a sub module that will be your starting point for future customization (this makes it
much easier to run/debug/test in your IDE).

* Copy all the resources (yml/xml) from the initializr-service to initializr-app src/main/resources

NOTE: this has the implication that you will need to periodically sync changes from the upstream
project and add them to this copy of application.yml

* Add required dependencies to the initializr-app pom.xml:

```xml
  <dependencies>
    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-generator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
    </dependency>
  </dependencies>
```

. Create a new Spring Boot application class in src/main/java (under com.company.io.spring.initializr)

```java
package com.company.io.spring.initializr;

import java.util.concurrent.Executor;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.AsyncConfigurerSupport;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

@SpringBootApplication
public class InitializrApp {

  public static void main(String[] args) {
    ApplicationContext ctx = SpringApplication.run(InitializrApp.class, args);
  }

  @Configuration
  @EnableAsync
  static class AsyncConfiguration extends AsyncConfigurerSupport {
    @Override
    public Executor getAsyncExecutor() {
      ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
      executor.setCorePoolSize(1);
      executor.setMaxPoolSize(5);
      executor.setThreadNamePrefix("initializr-");
      executor.initialize();
      return executor;
    }
  }
}
```

Verify these changes by executing the main from the IDE.  Right-click the InitializrApp Java file
and select > Debug 'InitializrApp'.  Again, visit http://localhost:8080 and review the running
application.

NOTE: You may have noticed that we included spring-boot-devtools in the dependencies.  This will
really help speed up local development along with the LiveReload plug-in.

If this is all working, make a change to the web template in initializr-web >
src/main/resources/templates/home.html - change "Spring Initializr" to "My Spring Initializr" and
select Build > Compile 'home.html' / command+shift+f9 (in IntelliJ).  Voila!

== Step 1: Let's add a 3rd party dependency

*Scenario*: You've discovered a great 3rd-party library you want all of your teams to start using
it.  You also want it to be available for selection from the Initializr.  In this example, we want
to use http://www.jasypt.org/[Jasypt] to encrypt properties in our properties files and we found the
perfect https://github.com/ulisesbocchio/jasypt-spring-boot[project] that does that for us:

. Modify the initializr-app :: src/main/resources/application.yml
.. Add a custom section (below Ops approx line 643):

```yml
    - name: Custom
      content:
        - name: Jasypt
          id: jasypt
          description: Provides Jasypt encryption support for property sources
          version: 1.6
          groupId: com.github.ulisesbocchio
          artifactId: jasypt-spring-boot-starter
```

NOTE: Since Spring Boot is not managing this dependency we have to specify the exact version OR
provide our own BOM.

. Select "Make Project" and wait for the reload
.. In the Dependencies field, you can now type 'Jasypt' or 'encrypt' and the dependency will be automatically show up.
. Verify your changes by generating a new project with the Web, Acutator and Jasypt dependencies.
. Unzip the generated project and add the following encrypted properties to the src/main/resources/application.properties:

....
secret.property=ENC(nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+)
secret.password=ENC(nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+)
....

. Execute the application:

....
% ./mvnw spring-boot:run -Dserver.port=9000 -Djasypt.encryptor.password=password
....

. Visit the applications http://localhost:9000/env/[env] URL.
Notice how Spring Boot masks the value if the property name contains password.

== Step 2: Lets add a VCS .ignore file

*Scenario*: Most of us are using Git right?  For those of us that are, a common step after
generating a project is to add a .gitignore file and setup Git.  Let's just have the Initializr
automatically do part of that for us.

SIDE: Technically, there is already an open https://github.com/spring-io/initializr/issues/131[request]
for this on the Initializr.  This is just one possible implementation.

* Visit https://www.gitignore.io/
* Type in: Java, Gradle, Maven, Eclipse and IntelliJ and hit "Generate" (or just visit https://www.gitignore.io/api/java,gradle,maven,eclipse,intellij)
* Copy the page contents and create a file named "gitignore" in initializr-generator - src/main/resources/templates

....
# Created by https://www.gitignore.io/api/java,maven,gradle,eclipse,intellij

### Maven ###
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties


### Eclipse ###

.metadata
bin/
tmp/
*.tmp
*.bak
*.swp
*~.nib
local.properties
.settings/
.loadpath
.recommenders

# Eclipse Core
.project

# External tool builders
.externalToolBuilders/

# Locally stored "Eclipse launch configurations"
*.launch

# PyDev specific (Python IDE for Eclipse)
*.pydevproject

# CDT-specific (C/C++ Development Tooling)
.cproject

# JDT-specific (Eclipse Java Development Tools)
.classpath

# Java annotation processor (APT)
.factorypath

# PDT-specific (PHP Development Tools)
.buildpath

# sbteclipse plugin
.target

# Tern plugin
.tern-project

# TeXlipse plugin
.texlipse

# STS (Spring Tool Suite)
.springBeans

# Code Recommenders
.recommenders/


### Intellij ###
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio and Webstorm
# Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

# User-specific stuff:
.idea/workspace.xml
.idea/tasks.xml
.idea/dictionaries
.idea/vcs.xml
.idea/jsLibraryMappings.xml

# Sensitive or high-churn files:
.idea/dataSources.ids
.idea/dataSources.xml
.idea/dataSources.local.xml
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml

# Gradle:
.idea/gradle.xml
.idea/libraries

# Mongo Explorer plugin:
.idea/mongoSettings.xml

## File-based project format:
*.iws

## Plugin-specific files:

# IntelliJ
/out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

### Intellij Patch ###
# Comment Reason: https://github.com/joeblau/gitignore.io/issues/186#issuecomment-215987721

# *.iml
# modules.xml
# .idea/misc.xml
# *.ipr


### Java ###
*.class

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*


### Gradle ###
.gradle
build/

# Ignore Gradle GUI config
gradle-app.setting

# Avoid ignoring Gradle wrapper jar file (.jar files are usually ignored)
!gradle-wrapper.jar

# Cache of project
.gradletasknamecache

# # Work around https://youtrack.jetbrains.com/issue/IDEA-116898
# gradle/wrapper/gradle-wrapper.properties
....

Adding the template alone will not have an effect, we have to change the Groovy generator code.

* in initializr-generator, modify io.spring.initializr.ProjectGenerator > doGenerateProjectStructure (approx line 157):

```groovy
        write(new File(dir, '.gitignore'), 'gitignore', model)
```

WARNING: Normally, this should have been enough to get the file template to be included but there is
an unusual side effect of Ant's zipfileset that excludes certain files (like .gitignore). We have
to change this default behavior before it will work.

* In initializr-web, modify io.spring.initializr.web.project.MainController > springZip (approx line 217):

```groovy
        zipfileset(dir: dir, includes: '**', excludes: wrapperScript, defaultexcludes: "no")
```

* Select the "Make Project" and wait for the UI reload.

* Generate a new application and unzip it.  You should now be able to verify that a .gitingore file
is included with Spring Boot.

== Step 3: Lets add a customizable README

*Scenario*: Since we are generating a starter Spring Boot application it might be a good idea to
include a customizable README with links to documentation, etc.

* Create a README.adoc file in the initializr-generator > src/main/resources/templates

....
= Spring Boot README

TBD

Generated on <% out.print new Date() %>
....

* in initializr-generator, modify io.spring.initializr.ProjectGenerator > doGenerateProjectStructure (appox line 157):

```groovy
        write(new File(dir, 'README.adoc'), 'README.adoc', model)
```

* Verify by selecting the "Make Project" and wait for the UI reload.  Then generate an application
of any kind and unzip to see the README.adoc

But wait, there is more that can be done.  Since the Initializr is using Groovy templates, it is
possible to get full access to the metadata model inside of the README.  We can enhance it to
include more information about the original generation process and even provide conditional
documentation:

....
= Spring Boot README

== ${name}

* Group: ${groupId}
* Artifact: ${artifactId}
* Java Version: ${javaVersion}

${description}

== Dependencies

<% compileDependencies.each { %>* ${it.groupId}:${it.artifactId}${it.version ? ":$it.version" : ""}
<% } %>

<% if (compileDependencies.find { it -> it.artifactId == 'jasypt-spring-boot-starter' }) { %>
=== Jasypt
To add encrypted properties, please refer to the following https://github.com/ulisesbocchio/jasypt-spring-boot[documentation].
<% } %>

----
Generated on <% out.print new Date() %>
....

FYI: You might have to touch the ProjectGenerator.groovy file to be able to force a Make Project to
occur (sometimes just modifying the template isn't enough for IntelliJ to think something has
changed).

* Make Project and wait for the UI reload.  This time, generate an application with the Jasypt
dependency and see that it contains the extra documentation link.

== Step 4: Wait a minute!  You've not been writing any unit tests! (Lets write some tests)

....
% mvn clean package
....

Well, at least we haven't broken anything (yet).  However, testing of the Initializer can be HARD
and its actually quite easy to break something.

* Add a test case to ProjectGeneratorTests.groovy (initializr-generator >
src/test/groovy/io/spring/initializr/generator)

```groovy
	@Test
	void customFilesWithDefaultProject() {
		def request = createProjectRequest('web')
		generateProject(request)
				.hasFile(".gitignore")
				.hasFile("README.adoc")
	}
```

* Run the JUnit tests and verify that you get a GREEN bar.  This verifies that both Step 2 and
Step 3 are actually generating a file as part of the project.

* Now lets add a test that verifies that the README.adoc actually contains the extra info when we
include Jasypt.  To do this well need to add an additional assetion to the built-in ProjectAssert that the tests are
already using.  This will make sure a specific value is found in the file passed in:

```groovy
	ProjectAssert assertFileContains(String localPath, String... expressions) {
		def candidate = file(localPath).text;
		for (String expression : expressions) {
			assertTrue "$expression has not been found in source file '$localPath'", candidate.contains(expression)
		}
		this
	}
```

We can now use this as part of a formal test in ProjectGeneratorTests.groovy (initializr-generator >
src/test/groovy/io/spring/initializr/generator):

```groovy
	@Test
	void readmeContainsExtraInfoWithJasyptDeps() {
		def dependency = new Dependency(id: 'jasypt', groupId: 'com.github.ulisesbocchio', artifactId: 'jasypt-spring-boot-starter', version: "1.6")
		dependency.facets << 'web'
		def metadata = InitializrMetadataTestBuilder.withDefaults()
				.addDependencyGroup('core', 'web', 'security', 'data-jpa')
				.addDependencyGroup('test', dependency).build()
		applyMetadata(metadata)

		def request = createProjectRequest('jasypt')

		generateProject(request)
				.hasFile("README.adoc")
				.assertFileContains("README.adoc", "=== Jasypt");
	}
```

NOTE: In the long run, it is arguably better to just create a brand new test case for your customized
behaviors - this should limit the merge conflicts that you have when the Initializr project matures
(and it will).  Remember what we're typically doing is highly customized behaviors that are unique to
our company or team.  These aren't likely to be adopted by the Initializr team, so we'll frequently
end up having to merge in changes from upstream.

== Step 5: Let's make it easier to generate a "standard" Microservice

*Scenario*: We want some standardization on the required starters for our team (for example, all
services need to use Actuator).  The default Initializr doesn't have any built-in support for groups
of dependencies, so lets add the ability to support this

* In initializr-web > src/main/resources/templates modify the home.html to include a selection
element for the various application archetypes we want to support (approx line 109):

```html
                    <!-- begin custom stuff -->
                    <div class="form-group">
                        <label for="archetypes" class="control-label">Select a Starter Archetype</label>
                        <select id="archetypes">
                            <option value="NONE">Ad hoc</option>
                            <option value="REST">Microservice (REST)</option>
                            <option value="FOO">Foo</option>
                            <option value="BAR">Bar</option>
                        </select>
                    </div>
                    <!-- end custom stuff -->
```

This modifies the default Initializr UI to include a Select field just above the "Search for
dependencies" field.  Our goal is to auto select dependencies for a specific application archetype.

* Add an change listener to this element in the src/main/resources/static/js start.js file
(approx line 267):

```javascript
    // begin custom changes
    $("#archetypes").on("change", function (e) {
        // this could be a little smarter...
        $("#starters div").remove();
        $("#dependencies input").prop('checked', false);
        var results = [];
        switch ($(this).find(":selected").val()) {
        case "REST":
            results = starters.get(['web','actuator','cloud-hystrix','security', 'jasypt', 'cloud-starter-sleuth', 'devtools']);
            break;
        case "FOO":
            results = starters.get(['thymeleaf', 'web', 'actuator', 'security', 'devtools']);
            break;
        case "BAR":
            results = starters.get(['batch']);
        }
        for (var i = 0; i < results.length; i++) {
            addTag(results[i].id, results[i].name);
            $("#dependencies input[value='" + results[i].id + "']").prop('checked', true);
        }
    });
    // end custom changes
```

* Click "Make Project" and verify that selecting the REST archetype now auto selects the predefined
starters.

Combined with being able to add our own custom dependencies we now have a solid base for quickly
generating Boot apps that are more in line with our team's guidelines and standards.  We can ensure
our teammates will be setup for success right out of the gate.

== Step 6: Let's enhance our Git support

*Scenario*: We already created a .gitignore file to support our VCS but what we'd really like is to
have the repo automatically created with the initial commit.  In fact, why not just go all the way
and push this first commit directly to GitHub?

* In the initializr-generator lets add a dependency to JGit to the pom.xml (approx line 31):

```xml
		<dependency>
			<groupId>org.eclipse.jgit</groupId>
			<artifactId>org.eclipse.jgit</artifactId>
			<version>4.4.0.201606070830-r</version>
		</dependency>
```

* Refresh the Maven dependencies.  This library will make it possible to initialize git and perform
a automated push, but first, lets make this an option that a user can select.  Add a checkbox to
the initializr-web form in src/main/resources/templates/home.html (approx line 38):

```html
                    <h3> Initialize Git Repo?
                        <input type="checkbox" id="initGit" name="initGit" tabindex="2">
                    </h3>
```

With a simple checkbox we can now toggle the decision to initialize a git repository
as part of the Generate.  To fully support this, we need to add the attribute to
the underlying model.

* Add a Boolean property to BasicProjectRequest.groovy in initializr-generator >
src/main/groovy/io/spring/initializr/generator (approx line 42):

```groovy
	Boolean initGit
```

Just adding this attribute now makes it available in the ProjectGenerator.

* Wrap the original gitignore write logic with a check and call out to a new
method to do the actual git init (approx line 158):

```groovy
if (request.initGit == true) {
  write(new File(dir, '.gitignore'), 'gitignore', model)
  gitSetup(dir, request)
}
```

And then add the new getSetup function:

```groovy
void gitSetup(File dir, ProjectRequest request) {
  Git git;
  try {
    // use ~/.github properties file
    Properties props = new Properties()
    File propFile = new File(System.properties['user.home'], ".github")
    propFile.withInputStream{ props.load(it) }

    // git init, add and commit
    git = Git.init().setDirectory(dir).call();
    git.add().addFilepattern(".").call();
    git.commit().setAll(true).setMessage("Initial commit by Initializr").call();

    // git remote and branch config
    StoredConfig config = git.getRepository().getConfig();
    config.setString(ConfigConstants.CONFIG_REMOTE_SECTION, "origin", "url", "${props.url}/${request.name}.git");
    config.setString(ConfigConstants.CONFIG_BRANCH_SECTION, "master", "remote", "origin");
    config.setString(ConfigConstants.CONFIG_BRANCH_SECTION, "master", "merge", "refs/heads/master");
    config.save();
  } catch (Exception ex) {
    publishProjectFailedEvent(request, ex)
    throw ex
  } finally {
    git?.close();
  }
}
```

NOTE: We found a slight issue with the build wrapper scripts and the git setup
related to the fact that the zipfileset process is marking them as executable
(after the git commit).  This causes git to see set the files as being modified
when you unzip the repo.  Our workaround is to modify the writeTextResource
process and add a call to setExecutable(true).

* In ProjectGenerator.groovy (approx line 321)

```groovy
writeTextResource(dir, 'gradlew', 'gradle/gradlew').setExecutable(true)
```

And (appox line 324):

```groovy
writeTextResource(dir, 'mvnw', 'maven/mvnw').setExecutable(true)
```

Now the files will be committed with 755.  Note, this approach might not work on
Windows systems.  If you unzip the generated project and do a git status and see
something not up to date, this is likely the cause.

Before we can actually test these changes, we need to perform a couple of manual
steps on GitHub.

* Go to your personal GitHub account and create an empty repo called
"demo-mytest"

* In your personal home folder, create a folder/file ~/.github

```
url=https://github.com/<your-github-name>
username=<your-oath-token>
password=
```

See https://help.github.com/articles/creating-an-access-token-for-command-line-use/
for more info on GitHub OAuth tokens.

* Restart the Initializr app and generate a Boot application with the Artifact
name "demo-mytest".  Make sure you select the Initialize Git Repo? [X] option.

WARNING: If you see errors about authentication it is likely your OAuth token
isn't valid or is not be read properly by the initGit function (use your
debugger to verify this).  You may also get a NoRemoteRepository exception.  In
this case, it is likely the Artifact name does not match the empty repository
name in GitHub.

By now, you should be able to see where this is all going.  We're very close to
having a completely automated repo provisioned directly from the Initializr.

== Step 7: Use the GitHub API to finalize automation

*Scenario*: We want to fully automate the work from Step 6.  Since GitHub
requires an empty repo to be created before it can be pushed, we'll have to
explore options as to how to do this from code.

* Add the http://github-api.kohsuke.org/[GitHub API] dependency to the
initializr-generator project pom.xml (right under the jgit dependency):

```xml
    <dependency>
      <groupId>org.kohsuke</groupId>
      <artifactId>github-api</artifactId>
      <version>1.76</version>
    </dependency>
```

* Refresh the IntelliJ dependency and add the logic to the gitSetup function in
ProjectGenerator.groovy (approx line 183):

```groovy
    // initialize the remote repo
    GitHub gitHub = GitHub.connect();
    gitHub.createRepository(request.name)
          .description(request.description)
          .create();
```

The GitHub API looks specifically for an oauth property in your ~/.github conf
file:

```
url=<your github home>
username=<your oauth token>
password=
oauth=<your oauth token>
```

* Restart the app and wait for the UI to refresh.

Assuming the changes take effect, you should now be able to generate from the
Initializr and have it automatically create the GitHub repo for you.  This was
actually pretty easy.

== Step 8:

*Scenario*: We usually setup a Travis-CI build manually after the first commit
but since Travis-CI has a REST API we want to see if we can also automate the
first build as part of the Initializr pipeline.

* First, make sure you have linked your GitHub account and Travis-CI.  Go to
https://travis-ci.org/ and sign in with your GitHub account.  TODO: We probably
need more details here (I don't remember exactly what I did to get the web site
setup completed).

* Once our accounts are linked we should install the Travis-CI CLI (we won't
use this directly from Initializr but it can be very useful during setup and
debugging).  Follow this
https://github.com/travis-ci/travis.rb#installation[guide] to complete the
install for your OS.

From the command-line, you should be able to login to Travis-CI using your
previously generated token from GitHub:

```
% travis login --org --github-token <your github token>
```

NOTE: Travis-CI needs very explicit account permission that you grant via the
GitHub access token.  You will want to verify that you have granted it
(Account -> Personal Access Tokens): repo(all), admin:org->read:org,
admin:repo_hook(all), and user->user:email.

* Generate a Travis-CI access token from the command line:

```
% travis token
```

Paste the token the that Travis-CI CLI generates into the .github conf file as
a property called `travisauth`.

```
url=<your github url>
username=<github auth token>
password=
oauth=<github auth token>
travisauth=<your travis token>
```

* For Travis-CI to work, the project needs to have a .travis.yml file added to
its root directory.  We can do this by adding a new template file (just like the
earlier steps).  In the initializr-generator > src/main/resources/templates add
a travis.yml file:

```yml
language: java
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
```

NOTE: By default, Travis-CI should be able to build this project without the
install/script customization but we ran into some issues with it running the
wrapper (mvnw).  By specifying the install/script steps we are explicitly
overriding the default behavior to avoid this issue.

* Next add the logic to the ProjectGenerator.groovy file to copy this template
during the generate step (approx line 173):

```groovy
if (request.initGit == true) {
  write(new File(dir, '.gitignore'), 'gitignore', model)
  write(new File(dir, '.travis.yml'), 'travis.yml', model)
  gitSetup(dir, request)
}
```

* Add a Boolean attribute to the BaseProjectRequest.groovy to allow us to turn
off Travis-CI integration (we won't hook it up to the UI right now):

```groovy
	Boolean initTravisCI = true
```

* Unfortunately we were unable to find a JVM implementation of the Travis-CI API,
so we will have to work with the REST interface directly.  To facilitate this,
we'll use the Spring RestTemplate.  That class is not currently available in the
generator, so we'll have to add a dependency to the project pom.xml (approx line
18):

```xml
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-web</artifactId>
</dependency>
```

* Force a Maven dependencies refresh.  Now add a some logic to the setupGit
method in ProjectGenerator.groovy to trigger Travis-CI setup:

```groovy
if (request.initTravisCI == true) {
  // you need to enable travis-ci before the first push for it to automatically build
  initTravisCI(props, request)
}
```

And then add a new initTravisCI method to the same class (approx line 222):

```groovy
void initTravisCI(Properties props, ProjectRequest request) {
  // setup travis-ci to automatically build on push
  String travisUrl = "https://api.travis-ci.org";
  RestTemplate restTemplate = new RestTemplate()

  HttpHeaders headers = new HttpHeaders();
  headers.setContentType(MediaType.APPLICATION_JSON)
  headers.set(HttpHeaders.ACCEPT, "application/vnd.travis-ci.2+json");
  // todo we could get auth token dynamically...
  headers.set(HttpHeaders.AUTHORIZATION, "token ${props.travisauth}")
  headers.set(HttpHeaders.USER_AGENT, "Travis/1.0")

  def users = restTemplate.exchange("${travisUrl}/users", HttpMethod.GET, new HttpEntity(headers), Object.class)
  // force sync so the project is visible to travis-ci
  def sync = restTemplate.exchange("${travisUrl}/users/sync", HttpMethod.POST, new HttpEntity<Object>(users, headers), Object.class)

  // now wait for the sync to finish...
  def isSyncing = true;
  while (isSyncing) {
    sleep(500)
    users = restTemplate.exchange("${travisUrl}/users/${users.body.user.id}", HttpMethod.GET, new HttpEntity(headers), Object.class)
    isSyncing = users.body.user.is_syncing
  }

  // get the repo id
  def repos = restTemplate.exchange("${travisUrl}/repos/${users.body.user.login}/${request.name}", HttpMethod.GET, new HttpEntity(headers), Object.class)
  // make the repo active (aka flick the repository switch on)
  String body = "{\"hook\":{\"id\":${repos.body.repo.id},\"active\":true}}"
  def hooks = restTemplate.exchange("${travisUrl}/hooks", HttpMethod.PUT, new HttpEntity<String>(body, headers), Object.class)
}
```

* Select Make Project and wait for the UI to refresh.  You should now be able to
generate a project from the Initializr that not only will create and push the
code to GitHub but a Travis-CI build will be setup.  If everything worked as
expected a build should be kicked off in a few minutes.

== Step 9:

https://docs.travis-ci.com/user/deployment/cloudfoundry



== Parking Lot Ideas

- Add Travis-CI Build status to the README.adoc
-- ex. [![Build Status](https://travis-ci.org/ssherwood/demo-travis9.svg?branch=master)](https://travis-ci.org/ssherwood/demo-travis9)
- SonarQube integration: https://docs.travis-ci.com/user/sonarqube/
- Add support for encrypted properties in Travis-CI: https://docs.travis-ci.com/user/encryption-keys/
